<?php
/**
 * @file
 * Main functions and hook implementations
 */
/**
 * Implements hook_token_info().
 */
function entityform_anonymous_token_info() {

  $tokens = _entityform_anonymous_get_provided_tokens();
  return array(
    'tokens' => array('entityform' => $tokens),
  );
}

/**
 * @param $tokens
 * @return array
 */
function _entityform_anonymous_get_provided_tokens() {
  $tokens['anonymous_submission_token'] = array(
    'name' => t('Submission Token'),
    'description' => 'Raw Secure token for anonymous submissions',
  );
  $tokens['anonymous_submission_view_link'] = array(
    'name' => t('Anonymous Submission View Link'),
    'description' => 'views anonymous submissions',
  );
  $tokens['anonymous_submission_edit_link'] = array(
    'name' => t('Anonymous Submission Edit Link'),
    'description' => 'views anonymous submissions',
  );
  $tokens['anonymous_submission_submit_link'] = array(
    'name' => t('Anonymous Submission Submit Link'),
    'description' => 'views anonymous submissions',
  );
  return $tokens;
}

/**
 * Implements hook_tokens().
 */
function entityform_anonymous_tokens($type, $tokens, array $data = array(), array $options = array()) {
  drupal_set_message('bobo');
  $return = array();
  if ($type == 'entityform' && !empty($data['entityform'])) {
    $entityform = $data['entityform'];
    $anonymous_token = _entityform_anonymous_get_token($entityform->entityform_id);
    $options = array(
      'absolute' => TRUE,
      'query' => array(
        'token' => $anonymous_token,
        'id' => $entityform->entityform_id,
      ),
    );
    $provided_tokens = array_keys(_entityform_anonymous_get_provided_tokens());
    $entityform_type = entityform_type_load($entityform->type);
    foreach ($tokens as $name => $original) {
      if (empty($entityform_type->data['anonymous_links'])) {
        // If this Entityform Type doesn't support tokens all should be blank.
        if (in_array($name, $provided_tokens)) {
          $return[$original] = '';
          continue;
        }
      }
      switch ($name) {
        case 'anonymous_submission_token':
          $return[$original] = $anonymous_token;
          break;
        case 'anonymous_submission_view_link';
          $return[$original] = url('entityform/' . $entityform->entityform_id, $options);
          break;
        case 'anonymous_submission_edit_link':
          $return[$original] = url("entityform/{$entityform->entityform_id}/edit", $options);
          break;
        case 'anonymous_submission_submit_link':
          $return[$original] = url("eform/submit/{$entityform->type}", $options);
          break;

      }
    }
  }

  return $return;
}

function _entityform_anonymous_get_token($entityform_id) {
  return md5(drupal_get_private_key() . $entityform_id);
}

function entityform_anonymous_entityform_access_alter(&$access, $op, $context) {
  // Only alter if $access not TRUE

  $account = $context['account'];
  $entityform = $context['entityform'];
  if (!$access && isset($entityform->uid) && $account->uid == 0 && $entityform->uid == 0) {
    if (_entityform_anonymous_user_submitted_form($entityform)) {
      if ($op == 'confirm') {
        $access = TRUE;
      }
      else {
        if (user_access("$op own entityform")) {
          // This is an anonymously submitted and the current user is anonymous

          $access = TRUE;
        }
      }
    }
  }
  drupal_set_message("$op access = $access");
}

function _entityform_anonymous_user_submitted_form($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  if (!empty($entityform_type->data['anonymous_links']) && !empty($_GET['token'])) {
    if ($_GET['token'] == _entityform_anonymous_get_token($entityform->entityform_id)) {
      return TRUE;
    }
    // @todo Message about bad token/link
  }
}

function entityform_anonymous_entityform_previous_submission_alter(&$submission, $type, $context) {
  $uid = $context['uid'];
  if (!$uid && empty($submission)) {
    $draft = $context['draft'];
    if (!empty($_GET['token']) && !empty($_GET['id'])) {
      if ($_GET['token'] == _entityform_anonymous_get_token($_GET['id'])) {
        // Correct token. Load the full entityform
        $entityform = entityform_load($_GET['id']);
        if ($entityform->draft == $draft && $entityform->type == $type) {
          $submission = $entityform;
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter(): entityform_type_form.
 */
function entityform_anonymous_form_entityform_type_form_alter(&$form, &$form_state, $form_id) {
  $entityform_type = $form['#entityform_type'];

  $form['data']['anonymous_set'] = array(
    '#type' => 'fieldset',
    '#title' => t('Anonymous Tracking'),
    '#collapsible' => TRUE,
    '#group' => 'additional_settings',
    '#weight' => 150,
  );
  $form['data']['anonymous_set']['anonymous_links'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide Anonymous Links'),
    '#default_value' => !empty($entityform_type->data['anonymous_links']),
    '#description' => t('Allow entityform submissions to be accessible via anonymous links. These links will be available as tokens.'),
  );
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Form id entityform_edit_form
 * Allow access to draft button if form allows anonymous submissions
 * @todo Should this "allow anonymous" drafts be a setting?
 */
function entityform_anonymous_form_entityform_edit_form_alter(&$form, &$form_state, $form_id) {
  if (user_is_anonymous()) {
    if (!isset($form['review'])) {
      $entityform_type = entityform_type_load($form['#bundle']);
      // Make sure for is draftable and not in Review mode
      if ($entityform_type->data['anonymous_links'] && $entityform_type->data['draftable']) {
        $form['actions']['save']['#access'] = TRUE;
      }
    }
  }
}