<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function entityform_notifications_form_entityform_settings_alter(&$form, &$form_state, $form_id) {
  $entityform_type = $form['#entityform_type'];
  _entityform_notifications_type_settings($form['entityform_type_defaults']['data']['notifications_set'], $entityform_type);
  //$form['entityform_type_defaults']['data']['notifications_set'] = $notifications_set;
  _entityform_remove_fieldsets_from_tree($form['entityform_type_defaults']['data'], array('entityform_type_defaults', 'data'));
}
/**
 * Implements hook_form_FORM_ID_alter()
 */
function entityform_notifications_form_variable_edit_form_alter(&$form, &$form_state) {
  $variable_id = is_array($form_state['build_info']['args'][0]) ? $form_state['build_info']['args'][0][0] : $form_state['build_info']['args'][0];
  if (substr($variable_id, 0, 11) == 'entityform_') {
    $form['tokens'] = array(
        '#markup' => theme('token_tree', array('token_types' => array('entityform'), 'global_types' => FALSE)),
        '#weight' => 99999
    );
  }
}
/**
 * Implements hook_form_FORM_ID_alter().
 */
function entityform_notifications_form_entityform_type_form_alter(&$form, &$form_state, $form_id) {
  $entityform_type = $form['#entityform_type'];
  _entityform_notifications_type_settings($form['data']['notifications_set'], $entityform_type);
  //$form['data'] ['notifications_set'] = $notifications_set;
  _entityform_remove_fieldsets_from_tree($form['data'], array('data'));

}
function _entityform_notifications_type_settings(&$notifications_fieldset, $entityform_type) {
  //****************NOTIFICATIONS FIELDSET SETTINGS *********************//
  $notifications_fieldset['notification_text'] = array(
      '#type' => 'textarea',
      '#title' => t('Email text'),
      '#default_value' => empty($entityform_type->data['notification_text']) ? '' : $entityform_type->data['notification_text'],
      '#description' => t('Text for Confirmation Email. DO NOT put HTML in this field'),
  );
  $notifications_fieldset['notify_emails'] = array(
      '#type' => 'textfield',
      '#title' => t('Notification emails'),
      '#default_value' => empty($entityform_type->data['notify_emails']) ? '' : $entityform_type->data['notify_emails'],
      '#description' => t('Enter emails that should be notified for each form submissions.'),
      '#element_validate' => array('_entityform_form_email_list_validate'),
  );
  //return $notifications_set;
}
